name: shelf_plus
description: Shelf Plus is a quality of life addon for your server-side development within the Shelf platform.
version: 0.0.2
repository: https://github.com/felixblaschke/shelf_plus

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  shelf_hotreload: ^0.0.2
  mime_type: ^1.0.0
  supercharged_dart: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  dio: ^4.0.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.1
  build_runner: ^2.0.1
