name: shelf_plus
description: Shelf Plus is a quality of life addon for your server-side development within the Shelf platform.
version: 1.2.3
repository: https://github.com/felixblaschke/shelf_plus

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  shelf_hotreload: ^1.0.1
  shelf_web_socket: ^1.0.1
  mime_type: ^1.0.0
  supercharged_dart: ^2.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dio: ^4.0.0
  json_annotation: ^4.1.0
  json_serializable: ^5.0.2
  build_runner: ^2.0.1
